version: '3'
services:
  db:
    build:
      context: ./docker/
      dockerfile: Dockerfile-mariadb103
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-utf8.cnf:/etc/mysql/conf.d/mysql-utf8.cnf
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_DATABASE: coral
      MYSQL_USER: coral
      MYSQL_PASSWORD: where-is-the-coral-reef
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-php56
    ports:
      - '8080:80'
    links:
      - db
volumes:
  mysqldata:
